### ISSUE TITLE
Blacklisted

### ISSUE THREAD

**Issue by phated** [laurent-le-graverend/gulp-lodash-autobuild#1]
This module doesn't use a gulp stream and modifies the filesystem itself, which goes against all gulp guidelines.  I need to add this to the blacklist, sorry.

**Comment by laurent-le-graverend** [comment]
Hi @phated , thanks for having a look here, I haven't properly used the stream since it fitted my needs.
I'll improve this.

What do you mean by blacklisted? from where?
